name: otus_course
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  vector_math: any
  async: ^2.11.0

dev_dependencies:
  mockito: ^5.4.0
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  sort_fabric:
    path: ./sort_fabric
